#!/bin/bash

CLASSPATH="compiler/classpath";

source "$CLASSPATH/MinimalClassPathDefinitionProvider.java"

import Compiler.Classpath.CoreJavaUtilProviderService;
import Compiler.Classpath.JavaCompilerBean;

JavaCompilerBean.java_compiler_compile_program "$@"
